# Generated by Django 5.0.7 on 2024-07-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_age', models.PositiveSmallIntegerField()),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('teacher_course', models.CharField(max_length=20)),
                ('teacher_class', models.CharField(max_length=20)),
                ('teacher_description', models.TextField()),
                ('teacher_occupation', models.CharField(max_length=20)),
                ('teacher_salary', models.DecimalField(decimal_places=3, max_digits=6)),
                ('teacher_hobby', models.CharField(max_length=20)),
                ('teacher_picture', models.CharField(max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers2', to='student.student')),
            ],
        ),
    ]
